name: Go Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.23.x]
        platform: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run tests
        run: |
          go test ./...

      - name: Build for ${{ matrix.platform }}
        run: |
          mkdir -p build/${{ matrix.platform }}
          GOARCH=${{ matrix.platform }} GOOS=linux go build -o build/${{ matrix.platform }}/magic-wan ./cmd

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: magic-wan-${{ matrix.platform }}
          path: build/${{ matrix.platform }}/magic-wan
