name: Test Python

on:
  push:
    branches:
      - '*'
#      - '!main'

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

#    - name: Install dependencies
#      run: pip install -r requirements.txt  # Adjust if needed

    - name: Run unit tests
      run: python magic-wan/etc/magicwan/python/calc_p2p_net.test.py
